// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7eEqlGc-dW3EG5U4JwO2AqS25BlBa6kY',
    appId: '1:289604528921:web:cf7328061522e735e9f388',
    messagingSenderId: '289604528921',
    projectId: 'neighborhood-connect-56dc4',
    authDomain: 'neighborhood-connect-56dc4.firebaseapp.com',
    databaseURL: 'https://neighborhood-connect-56dc4-default-rtdb.firebaseio.com',
    storageBucket: 'neighborhood-connect-56dc4.firebasestorage.app',
    measurementId: 'G-G89W2BVENE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE9qvoCCMiJMk9vh7UC9nG2zTd0VnhVfM',
    appId: '1:289604528921:android:e28d6634d7cafb20e9f388',
    messagingSenderId: '289604528921',
    projectId: 'neighborhood-connect-56dc4',
    databaseURL: 'https://neighborhood-connect-56dc4-default-rtdb.firebaseio.com',
    storageBucket: 'neighborhood-connect-56dc4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIfrBWSEtzmDVFtHUgknjdQLPZaks5SfY',
    appId: '1:289604528921:ios:a04c01017eb1e270e9f388',
    messagingSenderId: '289604528921',
    projectId: 'neighborhood-connect-56dc4',
    databaseURL: 'https://neighborhood-connect-56dc4-default-rtdb.firebaseio.com',
    storageBucket: 'neighborhood-connect-56dc4.firebasestorage.app',
    iosBundleId: 'com.example.neighborhoodConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIfrBWSEtzmDVFtHUgknjdQLPZaks5SfY',
    appId: '1:289604528921:ios:a04c01017eb1e270e9f388',
    messagingSenderId: '289604528921',
    projectId: 'neighborhood-connect-56dc4',
    databaseURL: 'https://neighborhood-connect-56dc4-default-rtdb.firebaseio.com',
    storageBucket: 'neighborhood-connect-56dc4.firebasestorage.app',
    iosBundleId: 'com.example.neighborhoodConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7eEqlGc-dW3EG5U4JwO2AqS25BlBa6kY',
    appId: '1:289604528921:web:61afba1b44dfb266e9f388',
    messagingSenderId: '289604528921',
    projectId: 'neighborhood-connect-56dc4',
    authDomain: 'neighborhood-connect-56dc4.firebaseapp.com',
    databaseURL: 'https://neighborhood-connect-56dc4-default-rtdb.firebaseio.com',
    storageBucket: 'neighborhood-connect-56dc4.firebasestorage.app',
    measurementId: 'G-2DSCRVTN93',
  );
}
